version: 2

jobs:
  checkout_and_compile:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/index-coop-private
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Fetch Dependencies
          command: yarn install
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile Contracts
          command: yarn build
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/index-coop-private
  test:
    docker:
      - image: circleci/node:10.11.0
    working_directory: ~/index-coop-private
    parallelism: 3
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Fetch solc version
          command: docker pull ethereum/solc:0.6.10
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Test RPC
          command: yarn chain
          background: true
      - run:
          name: Hardhat Test
          command: yarn test

  coverage:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/index-coop-private
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Fetch solc version
          command: docker pull ethereum/solc:0.6.10
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Coverage
          command: yarn coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
      - coverage:
          requires:
            - checkout_and_compile
