import { BigNumber } from "@ethersproject/bignumber";
import { ZERO } from "../../../utils/constants";
import { ether } from "../../../utils/common/index";
import { ASSETS } from "../../assetInfo"
import { exchanges, StrategyInfo } from "../../types";

export const strategyInfo: StrategyInfo = {
  YFI: {
    address: ASSETS.YFI.address,
    input: BigNumber.from(36096),
    maxTradeSize: ether(12.5),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  COMP: {
    address: ASSETS.COMP.address,
    input: BigNumber.from(5333443),
    maxTradeSize: ether(180),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  SNX: {
    address: ASSETS.SNX.address,
    input: BigNumber.from(157618913),
    maxTradeSize: ether(8000),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  MKR: {
    address: ASSETS.MKR.address,
    input: BigNumber.from(901310),
    maxTradeSize: ether(28),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  REN: {
    address: ASSETS.REN.address,
    input: BigNumber.from(881153018),
    maxTradeSize: ether(45000),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(900),
    currentUnit: ZERO,
  },
  KNC: {
    address: ASSETS.KNC.address,
    input: BigNumber.from(204545192),
    maxTradeSize: ether(40000),
    exchange: exchanges.KYBER,
    exchangeData: '0x61639d6ec06c13a96b5eb9560b359d7c648c7759',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  LRC: {
    address: ASSETS.LRC.address,
    input: BigNumber.from(1245991468),
    maxTradeSize: ether(15000),
    exchange: exchanges.UNISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(900),
    currentUnit: ZERO,
  },
  BAL: {
    address: ASSETS.BAL.address,
    input: BigNumber.from(10799858),
    maxTradeSize: ether(2000),
    exchange: exchanges.BALANCER,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(900),
    currentUnit: ZERO,
  },
  UNI: {
    address: ASSETS.UNI.address,
    input: BigNumber.from(519857388),
    maxTradeSize: ether(30000),
    exchange: exchanges.UNISWAP_V3,
    exchangeData: '0x000bb8',
    coolOffPeriod: BigNumber.from(900),
    currentUnit: ZERO,
  },
  AAVE: {
    address: ASSETS.AAVE.address,
    input: BigNumber.from(12800177),
    maxTradeSize: ether(1000),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  MTA: {
    address: ASSETS.MTA.address,
    input: BigNumber.from(28505551),
    maxTradeSize: ether(6000),
    exchange: exchanges.UNISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  SUSHI: {
    address: ASSETS.SUSHI.address,
    input: BigNumber.from(189272855),
    maxTradeSize: ether(100000),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  CREAM: {
    address: ASSETS.CREAM.address,
    input: BigNumber.from(739109),
    maxTradeSize: ether(30),
    exchange: exchanges.SUSHISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  },
  FARM: {
    address: ASSETS.FARM.address,
    input: BigNumber.from(561523),
    maxTradeSize: ether(220),
    exchange: exchanges.UNISWAP,
    exchangeData: '0x00',
    coolOffPeriod: BigNumber.from(600),
    currentUnit: ZERO,
  }
};