name: Publish to NPM

on: [push]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn chain
      - name: Run tests
        run: yarn test